---
language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
gemfile:
  - Gemfile
before_script:
  - |
    case "${TRAVIS_RUBY_VERSION}" in
      rbx*)
        gem install psych
        ;;
    esac
  - rake travis:before -t
script: rake travis
after_script:
  - rake travis:after -t
notifications:
  email:
    recipients:
      - devs@clearfit.com
    on_success: change
    on_failure: always
env:
  global:
  - secure: EeWqQpeDNLg34HzfMtGxL327DODTQ1jTwcTpzJ7ZBX/ZUeXyAHVgeDPudg1YU4lDohE
  - secure: ljohOhWJ0Yx9oL4EWd/22EX//Rn7dCiFpYNKDqeyuPNEc28UuXHZKuRNgMx1QUVGzBe
  - secure: V04rbN1i+o3vd35pj89DO/odzBcix6dKiNyIxDWkiLK41M5cyCrZpEibyiEI0qintRq
